server:
  port: 8763

spring:
  application:
    name: eureka-server

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka, http://eureka2:8762/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
  instance:
    hostname: eureka3
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
