server:
  port: 8762
spring:
  application:
    name: eureka-server # Eureka服务集群服务名要保持一致
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka, http://eureka3:8763/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    register-with-eureka: true
  instance:
    hostname: eureka2
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10